=== wobbly/NINCAL/DEVELOP/Frontline/NIN_Order_REVISED_2.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xsd:element name="nin">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="lforder" type="LFOrderType" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="LFOrderType">
    <xsd:sequence>
      <xsd:element name="lrnum" type="LRType" />
      <xsd:element name="orderdate" type="xsd:date" />
      <xsd:element name="mailername" type="xsd:string" />
      <xsd:element name="listnum" type="ListNumType" />
      <xsd:element name="listname" type="xsd:string" />
      <xsd:element name="selection" type="xsd:string" />
      <xsd:element name="qty" type="QtyType" />
      <xsd:element name="keycode" type="xsd:string" />
      <xsd:element name="ponum" type="xsd:string" />
      <xsd:element name="media" type="xsd:string" />
      <xsd:element name="shipcontact" type="xsd:string" />
      <xsd:element name="shipcompany" type="xsd:string" />
      <xsd:element name="shipaddr" type="xsd:string" />
      <xsd:element name="shipcity" type="xsd:string" />
      <xsd:element name="shipstate" type="xsd:string" />
      <xsd:element name="shipzip" type="xsd:string" />
      <xsd:element name="shipemail" type="xsd:string" />
      <xsd:element name="maildate" type="xsd:date" />
      <xsd:element name="shipdate" type="xsd:date" />
      <xsd:element name="shipvia" type="xsd:string" />
      <xsd:element name="oppm" type="PriceType" />
      <xsd:element name="selprice" type="PriceType" />
      <xsd:element name="specialselections" type="xsd:string" />
      <xsd:element name="specialinstructions" type="xsd:string" />
      <xsd:element name="opu" type="OpuType" />
      <xsd:element name="contact" type="xsd:string" />
      <xsd:element name="entirelist" type="xsd:string" />
      <xsd:element name="orderterms" type="xsd:string" />
      <xsd:element name="requesttype" type="xsd:string" />      
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="LRType">
    <xsd:restriction base="xsd:unsignedInt">
      <xsd:minInclusive value="1" />
      <xsd:maxInclusive value="999999999" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ListNumType">
    <xsd:restriction base="xsd:unsignedInt">
      <xsd:minInclusive value="1" />
      <xsd:maxInclusive value="999999" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="QtyType">
    <xsd:restriction base="xsd:unsignedLong">
      <xsd:minInclusive value="1" />
      <xsd:maxInclusive value="999999999999" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="PriceType">
    <xsd:restriction base="xsd:decimal">
      <xsd:maxInclusive value="99999.99" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="OpuType">
    <xsd:sequence>
      <xsd:element name="opulr" type="LRType" />
      <xsd:element name="opudate" type="xsd:date" />
      <xsd:element name="opuqty" type="QtyType" />
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== wobbly/NINCAL/DEVELOP/Frontline/test.XML
<?xml version="1.0"?>
<nin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NIN_Order_REVISED_2.xsd">
<lforder>
<lrnum>624955</lrnum>
<orderdate>06-23-2006</orderdate>
<mailername>Humane Society of the U.S.                                                                          </mailername>
<listnum>010286</listnum>
<listname>People for the Ethical Treatment                                                                    </listname>
<selection>Donors (6 Mos)                                                                                      </selection>
<qty>000010000</qty>
<keycode>                                                                                                    </keycode>
<ponum>126468                                                                                              </ponum>
<media>Email                                                                                               </media>
<shipcontact>Humane Society of the U.S.                                                                          </shipcontact>
<shipcompany>                                                                                                    </shipcompany>
<shipaddr>                                                                                                    </shipaddr>
<shipcity>               </shipcity>
<shipstate>  </shipstate>
<shipzip>          </shipzip>
<shipemail>                                                                                                    </shipemail>
<maildate>09-19-2006</maildate>
<shipdate>06-26-2006</shipdate>
<shipvia>See Special Instructions  </shipvia>
<oppm>     .00</oppm>
<selprice>     .00</selprice>
<specialselections>
</specialselections>
<specialinstructions>
Please supply starting and ending location of  fields                                               
as well as translation tables for anycode in file data.                                             
                                                                                                    
Mark e-mail: HPPLTW                                                                                 
                                                                                                    
Note: Pls e-mail file by 06/26. Thanks!                                                             
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
</specialinstructions>
<opu>
<opulr>622860</opulr>
<opudate>06-12-20060612</opudate>
<opuqty>000057000</opuqty>
</opu>
<contact>Joey Gamache                       </contact>
<orderterms>Exchange</orderterms>
<requesttype>New</requesttype>
</lforder>
<lforder>
<lrnum>624946</lrnum>
<orderdate>06-21-2006</orderdate>
<mailername>Animal Protection Institute                                                                         </mailername>
<listnum>010286</listnum>
<listname>People for the Ethical Treatment                                                                    </listname>
<selection>Donors (24 Mos)                                                                                     </selection>
<qty>000005000</qty>
<keycode>                                                                                                    </keycode>
<ponum>D03063111                                                                                           </ponum>
<media>Email                                                                                               </media>
<shipcontact>Animal Protection Institute                                                                         </shipcontact>
<shipcompany>                                                                                                    </shipcompany>
<shipaddr>                                                                                                    </shipaddr>
<shipcity>               </shipcity>
<shipstate>  </shipstate>
<shipzip>          </shipzip>
<shipemail>                                                                                                    </shipemail>
<maildate>07-10-2006</maildate>
<shipdate>06-21-2006</shipdate>
<shipvia>See Special Instructions  </shipvia>
<oppm>     .00</oppm>
<selprice>     .00</selprice>
<specialselections>
</specialselections>
<specialinstructions>
Ship To: DATA@PIDIMP.COM                                                                            
                                                                                                    
RUSH!! Pls ship today.                                                                              
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
</specialinstructions>
<contact>Joey Gamache                       </contact>
<orderterms>Exchange</orderterms>
<requesttype>New</requesttype>
</lforder>
</nin>
