=== wobbly/NINCAL/DEVELOP/ListMarketsProject/Notes/xml/BrokerReport.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" />

<xsd:element name="BrokerReport" type="BrokerReportType" />

<xsd:complexType name="BrokerType">
  <xsd:sequence>
    <xsd:element name="BrokerNumber" type="xsd:unsignedInt" use="required" />
    <xsd:element name="BrokerCntNumber" type="xsd:unsignedInt" />
    <xsd:element name="BrokerContact" type="xsd:string" />
    <xsd:element name="BrokerCompany" type="xsd:string" />
    <xsd:element name="BrokerFax" type="xsd:string" />
    <xsd:element name="BrokerEmail" type="xsd:string" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="OrderRecordType">
  <xsd:sequence>
    <xsd:element name="Account" type="AccountType" />
    <xsd:element name="LRRecord" type="LRRecordType" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ShippingRecordType">
  <xsd:sequence>
    <xsd:element name="Account" type="AccountType" />
    <xsd:element name="LRRecord" type="LRRecordType" />
    <xsd:element name="ShippingRecord" type="ShippingRecordType" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="NewLCRRecordType">
  <xsd:sequence>
    <xsd:element name="Account" type="AccountType" />
    <xsd:element name="LRRecord" type="LRRecordType" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="RecordType">
  <xsd:sequence>
    <xsd:element name="OrderRecord" type="OrderRecordType" minOccurs="0" />
    <xsd:element name="ShippingRecord" type="ShippingRecordType" minOccurs="0" />
    <xsd:element name="NewLCRRecord" type="NewLCRRecordType" minOccurs="0" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="MailerType">
  <xsd:sequence>
    <xsd:element name="MailerName" type="xsd:string" use="required"/>
    <xsd:element name="MailerStatus" type="xsd:string" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="AccountType">
  <xsd:sequence>
    <xsd:element name="List" type="xsd:string" use="required"/>
    <xsd:element name="Mailer" type="MailerType" use="required"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="LRRecordType">
  <xsd:sequence>
    <xsd:element name="LRNumber" type="xsd:unsignedInt" use="required"/>
    <xsd:element name="PONumber" type="xsd:string" use="required"/>
    <xsd:element name="Quantity" type="xsd:unsignedInt" />
    <xsd:element name="ReturnDate" type="xsd:date" />
    <xsd:element name="OrderDate" type="xsd:date" />
    <xsd:element name="ClearStat" type="xsd:string" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ShippingRecordType">
  <xsd:sequence>
    <xsd:element name="ShipQuantity" type="xsd:unsignedLong" />
    <xsd:element name="ShipDate" type="xsd:date" />
    <xsd:element name="ShipText" type="xsd:string" />
    <xsd:element name="ShipTracking" type="xsd:string" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="BrokerReportType">
  <xsd:sequence>
    <xsd:element name="Broker" type="BrokerType" use="required" />
    <xsd:element name="Records" type="RecordType" />
  </xsd:sequence>
</xsd:complexType>

=== wobbly/NINCAL/DEVELOP/ListMarketsProject/Notes/xml/BrokerReport.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="BrokerReport.xsl"?>


<BrokerReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BrokerReport.xsd">

  <Date>4-4-2006</Date>
  
  <Broker>
    <BrokerNumber>0105</BrokerNumber>
    <BrokerCntNumber>020</BrokerCntNumber>
    <BrokerContact>Carol Zippel</BrokerContact>
    <BrokerCompany>AB Data</BrokerCompany>
    <BrokerFax>4145405050</BrokerFax>
    <BrokerEmail>czippel@abdata.com</BrokerEmail>
  </Broker>
  
  <Records>
    <OrderRecord>
        <Account>
          <List>Freedom From Hunger</List>
          <Mailer>
            <MailerName>Technoserve</MailerName>
            <MailerStatus></MailerStatus>
          </Mailer>
        </Account>
        <LRRecord>
          <LRNumber>616780</LRNumber>
          <PONumber>D01020665</PONumber>
          <Quantity>13,940</Quantity>
          <ReturnDate>04/05/2006</ReturnDate>
          <OrderDate></OrderDate>
          <ClearStat>Pending List Owner Approval</ClearStat>
        </LRRecord>
    </OrderRecord>
    <OrderRecord>
        <Account>
          <List>Population Communications Intl</List>
          <Mailer>
            <MailerName>Technoserve</MailerName>
            <MailerStatus></MailerStatus>
          </Mailer>
        </Account>
        <LRRecord>
          <LRNumber>616779</LRNumber>
          <PONumber>D01020670</PONumber>
          <Quantity>13,940</Quantity>
          <ReturnDate>04/05/2006</ReturnDate>
          <OrderDate></OrderDate>
          <ClearStat>Pending List Owner Approval</ClearStat>
        </LRRecord>
    </OrderRecord>
    <OrderRecord>
        <Account>
          <List>EngenderHealth</List>
          <Mailer>
            <MailerName>Technoserve</MailerName>
            <MailerStatus>Bad Mailer Status</MailerStatus>
          </Mailer>
        </Account>
        <LRRecord>
          <LRNumber>616781</LRNumber>
          <PONumber>D01020664</PONumber>
          <Quantity>7,567</Quantity>
          <ReturnDate>04/05/2006</ReturnDate>
          <OrderDate></OrderDate>
	  <ClearStat>Pending List Owner Approval</ClearStat>
	</LRRecord>
    </OrderRecord>
    <ShippingRecord>
        <Account>
          <List>Friends of John Kerry</List>
          <Mailer>
            <MailerName>Bob Casey for Senate</MailerName>
            <MailerStatus></MailerStatus>
          </Mailer>
        </Account>
        <LRRecord>
          <LRNumber>615110</LRNumber>
          <PONumber>D01020520</PONumber>
          <Quantity></Quantity>
          <ReturnDate></ReturnDate>
          <OrderDate></OrderDate>
          <ClearStat></ClearStat>
        </LRRecord>
      <Shipping>
        <ShipQuantity>30,000</ShipQuantity>
        <ShipDate>03/22/2006</ShipDate>
        <ShipText>Email</ShipText>
        <ShipTracking></ShipTracking>
      </Shipping>
    </ShippingRecord>
    <NewLCRRecord>
        <Account>
          <List>Best Friends Animal Society</List>
          <Mailer>
            <MailerName>Habitat for Humanity</MailerName>
            <MailerStatus></MailerStatus>
          </Mailer>
        </Account>
        <LRRecord>
          <LRNumber>616877</LRNumber>
          <PONumber></PONumber>
          <Quantity>15,000</Quantity>
          <ReturnDate></ReturnDate>
          <OrderDate>03/31/2006</OrderDate>
          <ClearStat>Received</ClearStat>
        </LRRecord>
    </NewLCRRecord>
    <NewLCRRecord>
        <Account>
          <List>Best Friends Animal Society</List>
          <Mailer>
            <MailerName>Habitat for Humanity</MailerName>
            <MailerStatus>
            </MailerStatus>
          </Mailer>
        </Account>
        <LRRecord>
          <LRNumber>616878</LRNumber>
          <PONumber></PONumber>
          <Quantity>15,000</Quantity>
          <ReturnDate></ReturnDate>
          <OrderDate>03/31/2006</OrderDate>
          <ClearStat>Received</ClearStat>
        </LRRecord>
    </NewLCRRecord>
  </Records>
  
</BrokerReport>
